import { Resend } from 'resend';

const FROM = 'Budget Sathi <onboarding@resend.dev>';
const APP_URL = process.env.CLIENT_URL || 'http://localhost:5173';

// Lazy initialization — ensures dotenv has loaded before accessing the key
const getResend = () => new Resend(process.env.RESEND_API_KEY);

// EMAIL VERIFICATION


export const sendVerificationEmail = async (email, name, token) => {
  const link = `${APP_URL}/verify-email?token=${token}`;

  await getResend().emails.send({
    from: FROM,
    to: email,
    subject: 'Verify your Budget Sathi account',
    html: `
      <!DOCTYPE html>
      <html>
      <head><meta charset="UTF-8"></head>
      <body style="font-family:'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:40px 20px;">
        <div style="max-width:480px;margin:0 auto;background:#fff;border-radius:16px;padding:40px;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
          <h1 style="color:#9333ea;font-size:22px;margin:0 0 8px;">💰 Budget Sathi</h1>
          <p style="color:#6b7280;font-size:13px;margin:0 0 32px;">Your Personal Financial Companion</p>
          <h2 style="color:#111827;font-size:18px;margin:0 0 16px;">Hi ${name}, verify your email</h2>
          <p style="color:#374151;font-size:15px;line-height:1.6;margin:0 0 28px;">
            Click the button below to verify your email address and activate your account.
            This link expires in <strong>24 hours</strong>.
          </p>
          <a href="${link}" style="display:inline-block;background:#9333ea;color:#fff;text-decoration:none;padding:14px 32px;border-radius:50px;font-weight:600;font-size:15px;">
            Verify Email
          </a>
          <p style="color:#9ca3af;font-size:12px;margin:28px 0 0;">
            If you didn't create a Budget Sathi account, you can safely ignore this email.
          </p>
        </div>
      </body>
      </html>
    `,
  });
};

// MONTHLY REPORT EMAIL
export const sendMonthlyReportEmail = async (email, name, month, year, pdfBuffer) => {
  const monthName = new Date(year, month - 1).toLocaleString('en-US', { month: 'long' });

  await getResend().emails.send({
    from: FROM,
    to: email,
    subject: `Your ${monthName} ${year} Financial Report — Budget Sathi`,
    html: `
      <!DOCTYPE html>
      <html>
      <head><meta charset="UTF-8"></head>
      <body style="font-family:'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:40px 20px;">
        <div style="max-width:520px;margin:0 auto;background:#fff;border-radius:16px;padding:40px;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
          <h1 style="color:#9333ea;font-size:22px;margin:0 0 8px;"> Budget Sathi</h1>
          <p style="color:#6b7280;font-size:13px;margin:0 0 32px;">Your Personal Financial Companion</p>
          <h2 style="color:#111827;font-size:18px;margin:0 0 16px;">Hi ${name}, your monthly report is ready!</h2>
          <p style="color:#374151;font-size:15px;line-height:1.6;margin:0 0 16px;">
            Your financial summary for <strong>${monthName} ${year}</strong> is attached to this email as a PDF.
          </p>
          <p style="color:#374151;font-size:15px;line-height:1.6;margin:0 0 28px;">
            Log in to Budget Sathi to view your full interactive report, spending trends, and AI recommendations.
          </p>
          <a href="${APP_URL}/reports" style="display:inline-block;background:#9333ea;color:#fff;text-decoration:none;padding:14px 32px;border-radius:50px;font-weight:600;font-size:15px;">
            View Full Report
          </a>
          <p style="color:#9ca3af;font-size:12px;margin:28px 0 0;border-top:1px solid #f3f4f6;padding-top:20px;">
            Generated by Budget Sathi • This report is for informational purposes only.<br>
            To unsubscribe from monthly reports, update your preferences in Settings.
          </p>
        </div>
      </body>
      </html>
    `,
    attachments: pdfBuffer ? [
      {
        filename: `BudgetSathi_${monthName}_${year}.pdf`,
        content: Buffer.from(pdfBuffer).toString('base64'),
      }
    ] : [],
  });
};

// PASSWORD RESET
export const sendPasswordResetEmail = async (email, name, token) => {
  const link = `${APP_URL}/reset-password?token=${token}`;
  await getResend().emails.send({
    from: FROM,
    to: email,
    subject: 'Reset your Budget Sathi password',
    html: `
      <!DOCTYPE html><html><head><meta charset="UTF-8"></head>
      <body style="font-family:'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:40px 20px;">
        <div style="max-width:480px;margin:0 auto;background:#fff;border-radius:16px;padding:40px;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
          <h1 style="color:#9333ea;font-size:22px;margin:0 0 8px;">💰 Budget Sathi</h1>
          <p style="color:#6b7280;font-size:13px;margin:0 0 32px;">Your Personal Financial Companion</p>
          <h2 style="color:#111827;font-size:18px;margin:0 0 16px;">Hi ${name}, reset your password</h2>
          <p style="color:#374151;font-size:15px;line-height:1.6;margin:0 0 28px;">
            Click the button below to create a new password. This link expires in <strong>1 hour</strong>.
          </p>
          <a href="${link}" style="display:inline-block;background:#9333ea;color:#fff;text-decoration:none;padding:14px 32px;border-radius:50px;font-weight:600;font-size:15px;">Reset Password</a>
          <p style="color:#9ca3af;font-size:12px;margin:28px 0 0;">If you didn't request this, ignore this email. Your password will remain unchanged.</p>
        </div>
      </body></html>
    `,
  });
};

// PASSWORD CHANGE NOTIFICATION

export const sendPasswordChangedEmail = async (email, name) => {
  await getResend().emails.send({
    from: FROM,
    to: email,
    subject: 'Your Budget Sathi password was changed',
    html: `
      <!DOCTYPE html>
      <html>
      <head><meta charset="UTF-8"></head>
      <body style="font-family:'Segoe UI',sans-serif;background:#f9fafb;margin:0;padding:40px 20px;">
        <div style="max-width:480px;margin:0 auto;background:#fff;border-radius:16px;padding:40px;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
          <h1 style="color:#9333ea;font-size:22px;margin:0 0 8px;">Budget Sathi</h1>
          <p style="color:#6b7280;font-size:13px;margin:0 0 32px;">Your Personal Financial Companion</p>
          <h2 style="color:#111827;font-size:18px;margin:0 0 16px;">Hi ${name}, your password was changed</h2>
          <p style="color:#374151;font-size:15px;line-height:1.6;margin:0 0 16px;">
            Your account password was successfully changed. All other active sessions have been logged out.
          </p>
          <p style="color:#374151;font-size:15px;line-height:1.6;margin:0 0 28px;">
            If you did not make this change, please contact support immediately and secure your account.
          </p>
          <p style="color:#9ca3af;font-size:12px;margin:0;">
            Generated by Budget Sathi • Confidential Security Notice
          </p>
        </div>
      </body>
      </html>
    `,
  });
};
